DECLARE @SEARCH_TERM AS varchar(4000) = 'BINANCE_DATASET'

SELECT
	P.[OBJECT_ID],
	S.[NAME] AS [SCHEMA],
	P.[NAME] AS [PROCEDURE],
	P.[TYPE_DESC] AS [DESCRIPTION],
	OBJECT_DEFINITION([OBJECT_ID]) AS [OBJECT_DEFINITION],
	P.CREATE_DATE,
	P.MODIFY_DATE
FROM SYS.PROCEDURES AS P WITH (NOLOCK)
INNER JOIN SYS.SCHEMAS AS S WITH (NOLOCK)
	ON P.[SCHEMA_ID] = S.[SCHEMA_ID]
WHERE OBJECT_DEFINITION([OBJECT_ID]) LIKE CONCAT('%', @SEARCH_TERM, '%')

DECLARE @PROCEDURE_NAME AS varchar(128) = 'BINANCE_DATASET_LOAD'

EXECUTE sp_helptext @PROCEDURE_NAME
