DECLARE @TABLE AS varchar(128) = 'WEATHER_STATION_READING'

SELECT
	I.[OBJECT_ID],
	I.[NAME],
	I.[TYPE_DESC] AS [DESCRIPTION],
	C.[NAME] AS [COLUMN],
	T.[NAME] AS [TYPE],
	C.MAX_LENGTH,
	I.FILL_FACTOR,
	I.IS_DISABLED,
	I.IS_HYPOTHETICAL,
	I.IS_IGNORED_IN_OPTIMIZATION,
	I.IS_PADDED,
	I.IS_PRIMARY_KEY,
	I.IS_UNIQUE,
	I.IS_UNIQUE_CONSTRAINT,
	I.HAS_FILTER,
	IC.IS_DESCENDING_KEY,
	IC.IS_INCLUDED_COLUMN
FROM SYS.INDEXES AS I WITH (NOLOCK)
INNER JOIN SYS.INDEX_COLUMNS AS IC WITH (NOLOCK)
	ON
		I.[OBJECT_ID] = IC.[OBJECT_ID]
		AND I.INDEX_ID = IC.INDEX_ID
INNER JOIN SYS.COLUMNS AS C WITH (NOLOCK)
	ON
		IC.[OBJECT_ID] = C.[OBJECT_ID]
		AND IC.COLUMN_ID = C.COLUMN_ID
INNER JOIN SYS.TYPES AS T WITH (NOLOCK)
	ON C.SYSTEM_TYPE_ID = T.SYSTEM_TYPE_ID
WHERE
	IC.[OBJECT_ID] = (
		SELECT [OBJECT_ID]
		FROM SYS.OBJECTS WITH (NOLOCK)
		WHERE [NAME] = @TABLE
	)
